services:
  ollama-mi50:
    image: xxdoman/ollama-mi50:v0.35.1
    container_name: ollama-mi50
    restart: unless-stopped
    shm_size: 16g
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    device_cgroup_rules:
      - 'c 226:* rmw'
    networks:
      - ai-network
    volumes:
      - /home/models/ollama:/models
      - /home/ollama_data:/root
      - /home/ai_work:/workspace
    ports:
      - "11430:11434"
    environment:
      - OLLAMA_MODELS=/models
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_KV_CACHE_TYPE=q8_0
      - OLLAMA_FLASH_ATTENTION=1
      - OLLAMA_LLM_LIBRARY=rocm
      - HSA_OVERRIDE_GFX_VERSION=9.0.6
      - LD_LIBRARY_PATH=/usr/lib/ollama/rocm

networks:
  ai-network:
    external: true
